### ISSUE TITLE
How to add an express API and remove SSR?

### ISSUE THREAD

**Issue by empz** [mobxjs/react-mobx-boilerplate#2]
I don't need SSR but I'd like to drop in a simple API in express.
I'd like that in development I be able to just "yarn start" and the express server serve the frontend (with webpack-hot-module) and also server my /api endpoints

**Comment by srolel** [comment]
SSR is separate from everything else. A separate bundle is created when you `yarn run build-node`, and you use the method it exports (on your server) for SSR. 

Since the boilerplate uses `webpack-dev-server`, that's all you get. You can [proxy](https://webpack.github.io/docs/webpack-dev-server.html#proxy) to an existing API server. Another option would be to use `webpack-dev-middleware` in an express app, instead of `webpack-dev-server`.
